### ISSUE TITLE
Dispatcher installed by default?

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/tuulbox#71]
Per [setup instructions](https://github.com/JuulLabs/tuulbox#initialization), in order to "enable" logging a dispatcher needs to be installed:

```kotlin
Log.dispatcher.install(ConsoleLogger)
```

This makes it cumbersome for libraries to use Tuulbox Logging, as it requires that 3rd party libraries instruct their library consumers to install a dispatcher. If a default dispatcher came pre-installed, then libraries could use Tuulbox Logging and only direct their users to Tuulbox documentation if they want to customize the logging (but otherwise no setup would be necessary).

**Comment by cedrickcooke** [comment]
I don't really agree with this feature request. While `ConsoleLogger` is guaranteed to exist on all platforms, it's usually not a logger you'll actually want to release with for a number of potential reasons.

On Android, for example, you generally don't want to use `ConsoleLogger` in the first place, because your log level won't be accurately reflected in Logcat. `System.out` ends up as `Info` and `System.err` ends up as `error`, and all other log levels are coerced into these two.

Across all platforms, installing a default logger still adds a barrier to entry. For release/distributed builds you either want to remove logging or replace it with something that reports to analytics/crash reporting. In either case a default will force a new call to `Log.dispatcher.clear()`.

**Comment by twyatt** [comment]
> While `ConsoleLogger` is guaranteed to exist on all platforms, it's usually not a logger you'll actually want to release with for a number of potential reasons.

Agreed, `ConsoleLogger` was simply mentioned as an example, but I don't think it should be the default logger for all platforms. Was thinking something more along the lines of `ConsoleLogger` being the default for JVM projects, `LogcatLogger` (or whatever name we end up with) for Android projects, etc.

> Across all platforms, installing a default logger still adds a barrier to entry. For release/distributed builds you either want to remove logging or replace it with something that reports to analytics/crash reporting. In either case a default will force a new call to `Log.dispatcher.clear()`.

Fair point, and I also agree that potentially needing to call `Log.dispatcher.clear()` is not good.

---

Do you have an alternate idea for how to solve this problem then? As it remains very awkward for a library to have to instruct library consumers to install a logger if they want logging? Then again, perhaps that is desirable (to have logging for a library be opt-in)? I was always super annoyed with the automatic nature of SL4J.

**Comment by twyatt** [comment]
For Kable, as an example, I'm reluctant to switch to Tuulbox logging purely because if a library consumer doesn't install a logger then they won't even see warnings/errors — perhaps there is a middle ground where if a logger is not installed, that a mechanism similar to `ConsoleLogger` will be used internally in Tuulbox logging for error/warning level logs?

**Comment by cedrickcooke** [comment]
If you want default logging in your library, I think a better approach is to make the engine pluggable. I have an example of this here JuulLabs/kable#151. This way, library consumers get the system logger by default for your library, but if they're willing to do more configuration they can change the engine to a Tuulbox implementation. As an added bonus, it's configurable for fully custom log implementations that don't route through Tuulbox.

**Comment by twyatt** [comment]
https://github.com/JuulLabs/kable/pull/151 demonstrated a clean/effective way to address my concerns, which motivated the creation of this issue. This issue is no longer applicable and the engine approach is preferred.
